<script type="text/javascript">
    //<![CDATA[
    <?php if (Mage::helper('pureclarity_core')->isProduction()): ?>
    const target = "http://admin.pureclarity.net";
    <?php else: ?>
    const target = "http://staging01.pureclarity.net";
    <?php endif?>
    function pureclarity_magento_go_to_admin() {
        window.location.href = target;
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>