<script type="text/javascript">
    //<![CDATA[
    function pureclarity_magento_run_feed() {

        var url ='<?php echo $this->getPopupUrl() ?>'
        var win = new Window({
            className:'magento',
            title:'Run a Pureclarity feed now',
            url:url,
            width:700,
            height:500,
            minimizable:false,
            maximizable:false,
            showEffectOptions: {duration:0.4},
            hideEffectOptions:{duration:0.4}
        });
        win.setZIndex(100);
        win.showCenter(true);
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>