<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            body{
                font-family:helvetica;
            }
            p{
                margin:0;
                font-size:12px;
            }
            progress{
                width: 100%;
            }
            label.disabled{
                color:grey;
            }
            img.pureclarity_magento_loading_image{
                float:right;
            }
            img.pureclarity_magento_loading_image_hidden{
                display:none;
            }
        </style>
        <script type="text/javascript">

            var selectedFeeds = [];
            var completedFeeds = [];
            var isComplete = false;
            var lastPollComplete = true;

            function uiStartLoading(){
                // Disable UI elements and show loading image
                document.getElementById("pureclarity_magento_loading_image").className = "pureclarity_magento_loading_image";
                document.getElementById("pureclarity_magento_run_now").disabled = true;
                document.getElementById("pureclarity-magento-product-feed").disabled = true;
                document.getElementById("pureclarity-magento-category-feed").disabled = true;
                document.getElementById("pureclarity-magento-brand-feed").disabled = true;
            }

            function uiEndLoading(){
                // Enable UI elements and hide loading image
                document.getElementById("pureclarity_magento_loading_image").className = "pureclarity_magento_loading_image pureclarity_magento_loading_image_hidden";
                document.getElementById("pureclarity_magento_run_now").disabled = false;
                document.getElementById("pureclarity-magento-product-feed").disabled = false;
                document.getElementById("pureclarity-magento-category-feed").disabled = false;
                document.getElementById("pureclarity-magento-brand-feed").disabled = false;
            }

            function setProgress(feedtype, done, max, isComplete, isUploaded){
                // Set progress bar value for the given feed type
                var statusMessage = document.getElementById("status-message");
                if (!isComplete){
                    var percent = ((done/max) * 100).toFixed(0)
                    statusMessage.innerHTML = "Generating " + feedtype + " feed... (" + percent + "% done)";
                }
                else if (isComplete && !isUploaded){
                    statusMessage.innerHTML = feedtype + "feed generated. Uploading to PureClarity...";
                }
                else if (isComplete && isUploaded){
                    statusMessage.innerHTML = feedtype + " feed complete.";
                };

                // eid = "pureclarity-magento-feed-progress-" + feedtype;
                // progBar = document.getElementById(eid);
                // if(progBar){
                //     progBar.setAttribute("max", max);
                //     progBar.setAttribute("value", done);
                // }
            }

            function feedComplete(request){
                // Called when a feed AJAX returns
                isComplete = true;
                for (var i = 0; i<= selectedFeeds.length-1; i++){
                    if (request.responseURL.indexOf('feedtype=all') >= 0){
                        // Set the feed to complete and the progress to 100%
                        completedFeeds.push(selectedFeeds[i]);
                        setProgress(selectedFeeds[i], 1, 1, true, true);
                    }
                    if (completedFeeds.indexOf(selectedFeeds[i]) < 0)
                        isComplete = false;
                }
                if (isComplete == true){
                    uiEndLoading();
                }
            }

            
            function pollProgress(){
                if (lastPollComplete) {
                    lastPollComplete = false;
                    // Called every five seconds to update progress bars
                    progressUrl = "<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/adminhtml_runfeednow/getprogress'); ?>";
                    for (var i = 0; i <= selectedFeeds.length - 1; i++) {
                        // Get progress for each feed selected
                        var feedProgress = new XMLHttpRequest();
                        feedProgress.onreadystatechange = function () {
                            if (this.readyState == 4 && this.status == 200) {
                                if (this.responseText != ""){
                                    progress = JSON.parse(this.responseText);
                                    // Update progress bar
                                    setProgress(progress.name, progress.cur, progress.max, progress.isComplete, progress.isUploaded);
                                    if (progress.isComplete && progress.isUploaded){
                                        feedComplete(this);
                                    }
                                }
                            }
                            if (this.readyState == 4) {
                                lastPollComplete = true;
                            }
                        };
                        now = encodeURIComponent(new Date()); // Append time to force a cache miss
                        var thisFeedUrl = progressUrl + "?time=" + now + "&feedtype=" + selectedFeeds[i].toLowerCase();
                        feedProgress.open("GET", thisFeedUrl, true);
                        feedProgress.send();
                    }
                }
                if (!isComplete) {
                    // Keep going if we are not complete yet
                    setTimeout(pollProgress, 1000);
                }
            }


            function runFeeds(){

                // Init loading
                isComplete = false;
                uiStartLoading();
                setProgress(0, 1);

                var feedUrl = "<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/adminhtml_runfeednow/runselected'); ?>";
                
                var startfeed = new XMLHttpRequest();
                startfeed.onreadystatechange = function() {
                    if (this.readyState == 4 && this.status == 200) { feedComplete(this); }
                    if (this.readyState == 4 && this.status != 200) {
                        if (this.status == 409) {
                            alert("The feed is already running, please wait for it to finish before running it again.");
                        }
                        else {
                            if (this.responseText != "")
                                alert(this.responseText);
                            else
                                alert("The feed did not complete correctly. You may need to rerun this feed.");
                            feedComplete(this);
                        }
                    }
                };
                var now = encodeURIComponent(new Date());
                var thisFeedUrl = feedUrl + "?time=" + now + "&feedtype=all&storeid=" + selectedStore;
                startfeed.open("GET", thisFeedUrl, true);
                startfeed.send();
                    
                // Start polling for progress updates.
                lastPollComplete = true;
                setTimeout(pollProgress, 1000);
            }
        </script>
    </head>
    <body>
        <h4>Select the store and feeds you would like to generate:</h4>
        <p>
            Select Store:
        </p>
        <p>
            <select name="store_select" id="store_select" style="width:100%;">
                <?php foreach (Mage::app()->getWebsites() as $website): ?>
                <?php foreach ($website->getGroups() as $group): ?>
                <?php foreach ($group->getStores() as $store): ?>
                    <option value="<?php echo $store->getId(); ?>" ><?php echo $group->getName() . " - " . $store->getName() ?></option>
                <?php endforeach; ?>
                <?php endforeach; ?>
                <?php endforeach; ?>
            </select>
        </p>
        <br />
        
        <p><input type="checkbox" id="pureclarity-magento-product-feed"/><label for="pureclarity-magento-product-feed">Products</label></p>
        <progress id="pureclarity-magento-feed-progress-product" max="100" value="0"></progress>

        <p><input type="checkbox" id="pureclarity-magento-category-feed"/><label for="pureclarity-magento-category-feed">Categories</label></p>
        <progress id="pureclarity-magento-feed-progress-category" max="100" value="0"></progress>

        <p><input type="checkbox" id="pureclarity-magento-brand-feed"/><label for="pureclarity-magento-brand-feed">Brands</label></p>
        <progress id="pureclarity-magento-feed-progress-brand" max="100" value="0"></progress>

        <p>&nbsp;</p>
        <div id="status-box-product" style="display:none">
            <p>
                <strong>Status: <strong> <span id="product-status-message"></span>
            </p>
        </div>
        <div id="status-box-category" style="display:none">
            <p>
                <strong>Status: <strong> <span id="category-status-message"></span>
            </p>
        </div>
        <div id="status-box-brand" style="display:none">
            <p>
                <strong>Status: <strong> <span id="brand-status-message"></span>
            </p>
        </div>
        <p>
            <button id="pureclarity_magento_run_now" onclick="runFeeds()">Run selected feeds now</button>
            <img id="pureclarity_magento_loading_image" class="pureclarity_magento_loading_image pureclarity_magento_loading_image_hidden" src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>">
        </p>
    </body>
</html>
