<!-- Default pureclarity search box -->
<div id="search_mini_form">
    <div  id="int_pc_search" class="input-box">
        <label for="search"><?php echo $this->__('Search') ?></label>
        <input id="search" type="search" class="input-text required-entry" maxlength="128" placeholder="Search entire store here..." autocomplete="off">
        <button id="pc_searchbutton" type="button" title="Search" class="button search-button"><span><span>Search</span></span></button>
    </div>
</div>