<?php $_productInformation = Mage::getModel('core/session')->getPCCheckoutUpdateItems();

//var_dump($_productInformation);

?>
<?php if ($_productInformation): ?>
<script type="text/javascript">
    <?php
        foreach($_productInformation as $product):
    ?>_pc('product_set_basket', {
        id: "<?php echo $product->getId();?>",
        quantity: "<?php echo $product->getQuantity();?>"
    });<?php
        endforeach;
    ?>
    
</script>
<?php Mage::getModel('core/session')->unsPCCheckoutUpdateItems(); ?>
<?php endif;